### ISSUE TITLE
Incorrect checking of $forceBreakWord

### ISSUE THREAD

**Issue by tjaart9** [BelniakMedia/craft-excerptify#1]
https://github.com/BelniakMedia/craft-excerptify/blob/acf670a32eafdd0c9a1c338a1e40ea6858207cd9/src/twigextensions/ExcerptifyTwigExtension.php#L53

I believe it should be `if (! $forceBreakWord)`.

**Comment by tjaart9** [comment]
@RickKukiela Ignore this.  Sorry.  It would help if I rtfm.  My bad.  🙈

**Comment by RickKukiela** [comment]
@tjaart9 even though you found a work around by passing `$forceBreakWord` to `true` this is definitely unintended. I have updated the code to version 1.0.1 that will just return back the string passed to it when the character count is already lower than the `$characterCount` argument.

Thank you for the report :)
