### ISSUE TITLE
Last word is lost if text is shorther than $characterCount already

### ISSUE THREAD

**Issue by tjaart9** [BelniakMedia/craft-excerptify#2]
https://github.com/BelniakMedia/craft-excerptify/blob/acf670a32eafdd0c9a1c338a1e40ea6858207cd9/src/twigextensions/ExcerptifyTwigExtension.php#L64

Assuming you set `$forceBreakWord` to `false`...

If the text that is being shortened is shorter than `$characterCount` already, the last word in `$text` is lost even though it would fit into `$characterCount`.  You'll need to add an extra `if ()` to NOT trim to the last space if the remaining `$text` is shorter than `$characterCount`.

**Comment by RickKukiela** [comment]
I didn't realize there was two open issues about this I just replied to the other issue (#1) that you are right and I have deployed a fix in the form of version 1.0.1.

Thanks!

**Comment by tjaart9** [comment]
> I have deployed a fix in the form of version 1.0.2.

@RickKukiela Thank you.  :-)

**Comment by RickKukiela** [comment]
Actually it was 1.0.1 not sure why I put .2 lol.
